"""Golden digests for both V3.0 label generators.

Three code comments tell a maintainer that changing the join, the tie-break, the
fallback or the line format means bumping `_GENERATION_VERSION`. Nothing else
enforces that: the manifest notices a *changed version*, never a changed
*generator*. These digests are what fail when the output moves.

A failure here is not automatically a bug. It means the generated bytes changed:
confirm that was intended, bump the model's `_GENERATION_VERSION` so every cached
directory regenerates, then update the digest below.
"""

import hashlib
from pathlib import Path

import pytest

import birdnet.acoustic.models.v3_0.model as acoustic_model
import birdnet.geo.models.v3_0.model as geo_model
from birdnet.utils.label_manifest import LabelInput, sha256_bytes

# Deliberately small and hand-written: one localized name, one blank cell falling
# back to English, one species missing from the taxonomy entirely.
_TAXONOMY = (
  b"species_code,sci_name,com_name,common_name_de\n"
  b"code1,Scivia one,Robin US,Rotkehlchen\n"
  b"code2,Scivia two,Sparrow US,\n"
)
_GEO_LABELS = (
  b"code1\tScivia one\tRobin\ncode2\tScivia two\tSparrow\ncode9\tScivia nine\tEagle\n"
)
_ACOUSTIC_LABELS = (
  b"sci_name;com_name\r\nScivia one;Robin\r\nScivia two;Sparrow\r\n"
  b"Scivia nine;Eagle\r\n"
)


def _digest(path: Path) -> str:
  return hashlib.sha256(path.read_bytes()).hexdigest()


def _prepare(
  monkeypatch: pytest.MonkeyPatch,
  module: object,
  tmp_path: Path,
  labels: bytes,
  languages: dict[str, str],
) -> Path:
  raw = tmp_path / "labels_raw"
  raw.write_bytes(labels)
  taxonomy = tmp_path / "taxonomy.csv"
  taxonomy.write_bytes(_TAXONOMY)
  lang_dir = tmp_path / "labels"

  monkeypatch.setattr(module, "_LABELS_RAW_PATH", raw)
  monkeypatch.setattr(module, "_LABELS_DL_SIZE", len(labels))
  monkeypatch.setattr(module, "_LABELS_DL_SHA256", sha256_bytes(labels))
  monkeypatch.setattr(module, "get_taxonomy_v3_path", lambda: taxonomy)
  monkeypatch.setattr(module, "_LANGUAGE_TO_COLUMN", languages)
  monkeypatch.setattr(
    module,
    "get_taxonomy_v3_input",
    lambda: LabelInput(
      path=taxonomy,
      url="https://example.test/taxonomy.csv",
      size=len(_TAXONOMY),
      sha256=sha256_bytes(_TAXONOMY),
    ),
  )
  return lang_dir


@pytest.mark.no_tf
def test_geo_generated_bytes_are_unchanged(
  tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
  languages = {"en_us": "com_name", "de": "common_name_de"}
  lang_dir = _prepare(monkeypatch, geo_model, tmp_path, _GEO_LABELS, languages)

  class _D(geo_model.GeoDownloaderBaseV3_0):
    @classmethod
    def _get_lang_dir(cls) -> Path:
      return lang_dir

  _D._generate_lang_files()

  assert _digest(lang_dir / "en_us.txt") == (
    "cbbae83301836112d04af123702481273859c96684f1b1a5977c4ef2e7a5b87f"
  )
  assert _digest(lang_dir / "de.txt") == (
    "47199c51321e46f3c6c970c60b01bf41f7c8b0208ff5e54a98e1504d4b3a3370"
  )


@pytest.mark.no_tf
def test_acoustic_generated_bytes_are_unchanged(
  tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
  languages = {"en_us": "com_name", "de": "common_name_de"}
  lang_dir = _prepare(
    monkeypatch, acoustic_model, tmp_path, _ACOUSTIC_LABELS, languages
  )

  class _D(acoustic_model.AcousticDownloaderBaseV3_0):
    @classmethod
    def _get_lang_dir(cls) -> Path:
      return lang_dir

  _D._generate_lang_files()

  assert _digest(lang_dir / "en_us.txt") == (
    "cbbae83301836112d04af123702481273859c96684f1b1a5977c4ef2e7a5b87f"
  )
  assert _digest(lang_dir / "de.txt") == (
    "47199c51321e46f3c6c970c60b01bf41f7c8b0208ff5e54a98e1504d4b3a3370"
  )
