name: CI

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-dl-models:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          [
            ubuntu-slim,
            ubuntu-24.04,
            ubuntu-24.04-arm,
            macos-15,
            macos-15-intel,
            windows-2025,
          ]
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python -m pip install uv build --upgrade
          python -m uv pip install twine build --upgrade
          python -m uv pip install --system .[tests]

      - name: Download models
        run: |
          pytest -m "load_model" -n auto

  build-and-test-no-litert:
    needs: build-and-dl-models
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          [
            ubuntu-slim,
            ubuntu-24.04,
            ubuntu-24.04-arm,
            macos-15,
            macos-15-intel,
            windows-2025,
          ]
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python -m pip install uv build --upgrade
          python -m uv pip install twine build --upgrade
          python -m uv pip install --system .[tests]

      # - name: Run linters
      #   run: |
      #     ruff check src/birdnet
      #     ruff check src/birdnet_tests

      # - name: Type checking
      #   run: mypy

      - name: Run tests
        run: |
          pytest -m "not load_model and not repro and (not litert and not gpu)" -n auto

      - name: Test build
        run: |
          python -m build -o dist/
          python -m twine check dist/*

  build-and-test-with-litert:
    needs: build-and-dl-models
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [
            ubuntu-slim,
            ubuntu-24.04,
            ubuntu-24.04-arm,
            macos-15,
            # intel mac and windows not supported for litert
          ]
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python -m pip install uv build --upgrade
          python -m uv pip install --system .[tests,litert]

      # - name: Run linters
      #   run: |
      #     ruff check src/mel_cepstral_distance
      #     ruff check src/mel_cepstral_distance_tests

      # - name: Type checking
      #   run: mypy

      - name: Run tests
        run: |
          pytest -m "not load_model and not repro and litert" -n auto
